version: "3.9"

services:
  test-api-server:
    image: nginx
    volumes:
      - ./test-api-server.conf:/etc/nginx/conf.d/default.conf
      - ./test_responses:/test_responses
    ports:
      - "8080:80"

  ariadne:
    image: test-ariande-perf
    build: ./test_ariadne
    depends_on:
      - test-api-server
    environment:
      TEST_SERVER_URI: "http://test-api-server:80"
    ports:
      - "8081:8000"

  apollo:
    image: test-apollo-perf
    build: ./test_apollo
    environment:
      TEST_SERVER_URI: "http://test-api-server:80"
    depends_on:
      - test-api-server
    ports:
      - "8082:4000"
