version: "3.9"

services:
  test-api-server:
    image: nginx
    volumes:
      - ./test-api-server.conf:/etc/nginx/conf.d/default.conf
      - ./test_responses:/test_responses
    ports:
      - "8080:80"
