version: "3.9"

services:
  test-api-server:
    image: nginx
    volumes:
      - ./test-api-server.conf:/etc/nginx/conf.d/default.conf
      - ./test_responses:/test_responses
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.test_api_server.rule=Host(`localhost`)"
      - "traefik.http.routers.test_api_server.entrypoints=test_api_server"  

  ariadne:
    image: test-ariande-perf
    build: ./test_ariadne
    depends_on:
      - test-api-server
    environment:
      TEST_SERVER_URI: "http://test-api-server:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ariadne.rule=Host(`localhost`)"
      - "traefik.http.routers.ariadne.entrypoints=ariadne"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G  

  apollo:
    image: test-apollo-perf
    build: ./test_apollo
    environment:
      TEST_SERVER_URI: "http://test-api-server:80"
    depends_on:
      - test-api-server
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.apollo.rule=Host(`localhost`)"
      - "traefik.http.routers.apollo.entrypoints=apollo"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G


  tartiflette_aiohttp:
    build: ./test_tartiflette_aiohttp
    depends_on:
      - test-api-server
    environment:
      TEST_SERVER_URI: "http://test-api-server:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tartiflette.rule=Host(`localhost`)"
      - "traefik.http.routers.tartiflette.entrypoints=tartiflette"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  graphene:
    image: test-graphene-perf
    build: ./test_graphene
    depends_on:
      - test-api-server
    environment:
      TEST_SERVER_URI: "http://test-api-server:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.graphene.rule=Host(`localhost`)"
      - "traefik.http.routers.graphene.entrypoints=graphene"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.test_api_server.address=:8008"
      - "--entrypoints.ariadne.address=:8081"
      - "--entrypoints.apollo.address=:8082"
      - "--entrypoints.tartiflette.address=:8083"
      - "--entrypoints.graphene.address=:8084"
    ports:
      - "8008:8008"
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
      - "8084:8084"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"